---
title: "Kansas City Mental Health Survey 2024"
author: Office of Population Health Science
format:
  typst:
    template-partials:
      - typst-show.typ
      - typst-template.typ
    execute:
      echo: false
      include: false
---

```{r warning=FALSE}
library(tidyverse)
```

```{r}
dir.create("figs")
```

```{r}
# Load data
samp <- readRDS("../../data/2-final/sample_data_&_plots.rds")
mh <- readRDS("../../data/2-final/mh_report_data_&_plots.rds")
```

```{r}
# Assemble figure captions
caps <- mh$caps |>
  mutate(sample_size = paste0("N = ", sample_size, ".")) |>
  tidyr::unite(col = cap, caption, sample_size, sep = " ")
```

```{r}
# Sample plots
ggsave(
  "figs/sex.png", samp$sex$fig2,
  width = 3.75, height = 2.5
)
ggsave(
  "figs/age.png", samp$age$fig2,
  width = 3.75, height = 2.5
)
ggsave(
  "figs/pyramid.png", samp$age_sex$fig,
  width = 7, height = 2.5
)
ggsave(
  "figs/race-ethn-all.png", samp$race_ethn_all$fig,
  width = 6.5, height = 2.5
)
ggsave(
  "figs/race-ethn-bwo.png", samp$race_ethn_bwo$fig2,
  width = 6.5, height = 2.5
)
ggsave(
  "figs/hispanic.png", samp$hispanic_origin$fig2,
  width = 6.5, height = 2.5
)
ggsave(
  "sample-map.png", samp$sample_map$fig,
  width = 4.5, height = 7
)
```

```{r}
# Q4 subquestions
q <- paste0("q4_", 1:4)
lapply(q, \(x) {
  nm <- paste0("figs/", sub("_", "-", x), ".png")
  fig <- mh$figs[[x]]
  ggsave(nm, fig, width = 6.5, height = 2.5)
})
```

```{=typst}
#import "typst-template.typ": rectwhite, rectgrey

#show heading: set align(center)
```

```{=typst}
#page[
  = Introduction
  
  #v(.5in)
  
  #show heading: set align(left)
  
  #grid(
    columns: (2fr, 3fr),
    column-gutter: .25in,
    rectgrey(height: 7.75in)[
      == Purpose
      The intended purpose of the Mental Health Survey is to gain a better understanding of Kansas City residents’ perception of their own mental health and behaviors. The results of this survey will be used for data driven decision making for program design and to identify interventions needed to support the Mental Health Initiatives. The survey supports Public Health Key Concept #1 in the KC Spirit Playbook which includes improving the mental health of Kansas City residents.
      
      == Methodology
      The Mental Health Survey was designed by the Office of Population Health Science and conducted by ETC Institute. The survey was mailed out in Quarter 3 of 2024 to 4,000 households with a response rate just over 16%. Recipients of the survey were selected on age, gender, race, and geographic location based off the demographic breakdown for Kansas City according to data collected in the 2020 Census. Surveys were made available in and Spanish with additional languages being available via phone. Survey results were scored and summarized by the Office of Population Health upon receipt of raw data.
    ],
    figure(
      image("sample-map.png", height: 7.35in),
      caption: [`r samp$sample_map$cap`]
    )
  )
]
```

```{=typst}
#show heading: set align(center)

#page[
  = Survey Sample Demographics
  == Age and Sex
  
  #v(.5in)
  
  #grid(
    columns: 2, rows: 3,
    column-gutter: .5in,
    row-gutter: .5in,
    grid.cell(
      colspan: 2,
      rectwhite[
        The plots in this section show the demographic profile of the survey sample in comparison to the overall Kansas City population. The survey was completed by 648 residents. The survey sample closely reflects the city's population by sex, race, and Hispanic origin. The age of the sample skews older than the city's population, which may be the result of older citizens being more willing to respond to surveys (or something).
        
        Dark vertical lines on some bars indicate the estimated citywide percentage of the population category sampled. Citywide population estimates were taken from the 2023 5-Year American Community Survey conducted by the US Census Bureau.
      ]
    ),
    figure(
      image("figs/sex.png"),
      caption: [`r samp$sex$cap`]
    ),
    figure(
      image("figs/age.png"),
      caption: [`r samp$age$cap`]
    ),
    grid.cell(
      colspan: 2,
      rectgrey[
        #figure(
          image("figs/pyramid.png"),
          caption: [`r samp$age_sex$cap`]
        )
      ]
    )
  )
]
```

```{=typst}
#page[
  == Race and Hispanic Origin
  
  #v(.5in)
  
  #rectwhite[
    #figure(
      image("figs/race-ethn-bwo.png"),
      caption: [`r samp$race_ethn_bwo$cap`]
    )
  ]
  
  #v(.5in)
  
  #rectgrey[
    #figure(
      image("figs/hispanic.png"),
      caption: [`r samp$hispanic_origin$cap`]
    )
  ]
]
```

```{=typst}
#page[
  = Mental Health Questions
  == Anxiety
  
  #v(.5in)
  
  #lorem(50)
  
  #rectgrey[
    #figure(
      image("figs/q4-1.png"),
      caption: [`r caps$cap[caps$number == "4_1"]`]
    )
  ]
  
  #v(.5in)
  
  #lorem(50)
  
  #rectwhite[
    #figure(
      image("figs/q4-2.png"),
      caption: [`r caps$cap[caps$number == "4_2"]`]
    )
  ]
]
```




















```{=typst}
#page[
  = Introduction

  `r extract_text(doc, "intro", "p", "typst")`

  = Executive summary

  `r extract_text(doc, "exec", "p", "typst")`

  = Survey methodology

  `r extract_text(doc, "method", "p", "typst")`

  #v(.25in)

  #figure(
    image("img/map-respondents.png", height: 6in),
    caption: [`r caps$map_respondents`]
  ) <fig-map-resp>
]
```

```{=typst}
#page[
  = Survey sample

  `r extract_text(doc, "sample", "p", "typst")`

  #v(.25in)

  #figure(
    table(image("img/tbl-dist.png", height: 1.96in)),
    caption: [`r caps$tbl_dist`]
  )

  #v(.25in)

  #figure(
    image("img/demo-sex2.png", height: 2.5in),
    caption: [`r caps$birth_sex`]
  )

  #v(.25in)

  #figure(
    image("img/demo-age.png", height: 3in),
    caption: [`r caps$age`]
  )

  #v(.25in)

  #figure(
    image("img/demo-age-str.png", height: 3in),
    caption: [`r caps$age_str`]
  )

  #v(.25in)

  #figure(
    image("img/demo-race-eth.png", height: 4in),
    caption: [`r caps$race_ethnicity`]
  )

  #v(.25in)

  #figure(
    image("img/demo-race-col.png", height: 4in),
    caption: [`r caps$race_collapsed`]
  )

  #v(.25in)

  #figure(
    image("img/demo-hisp.png", height: 4in),
    caption: [`r caps$hispanic_origin`]
  )
]
```

```{=typst}
#page[
  = Results

  == Personal mental health

  `r extract_text(doc, "personal", "p", "typst")`

  #v(.25in)

  ==== `r cb$viz$header[cb$viz$var == "q4_1"]`

  #figure(
    image("img/q4-1.png", height: 3.5in),
    caption: [`r caps$q4_1`]
  )

  `r extract_text(doc, "q4-1", "p", "typst")`

  #v(.25in)

  ==== `r cb$viz$header[cb$viz$var == "q4_2"]`

  #figure(
    image("img/q4-2.png", height: 3.5in),
    caption: [`r caps$q4_2`]
  )

  `r extract_text(doc, "q4-2", "p", "typst")`

  #v(.25in)

  ==== `r cb$viz$header[cb$viz$var == "q4_3"]`

  #figure(
    image("img/q4-3.png", height: 3.5in),
    caption: [`r caps$q4_3`]
  )

  `r extract_text(doc, "q4-3", "p", "typst")`

  #v(.25in)

  ==== `r cb$viz$header[cb$viz$var == "q4_4"]`

  #figure(
    image("img/q4-4.png", height: 3.5in),
    caption: [`r caps$q4_4`]
  )

  `r extract_text(doc, "q4-4", "p", "typst")`

  #v(.25in)

  ==== `r cb$viz$header[cb$viz$var == "q5"]`

  #figure(
    image("img/q5.png", height: 3.5in),
    caption: [`r caps$q5`]
  )

  `r extract_text(doc, "q5", "p", "typst")`

  #v(.25in)

  ==== `r cb$viz$header[cb$viz$var == "q6"]`

  #figure(
    image("img/q6.png", height: 3.5in),
    caption: [`r caps$q6`]
  )

  `r extract_text(doc, "q6", "p", "typst")`

  #v(.25in)

  ==== `r cb$viz$header[cb$viz$var == "q7"]`

  #figure(
    image("img/q7.png", height: 3.5in),
    caption: [`r caps$q7`]
  )

  `r extract_text(doc, "q7", "p", "typst")`

  #v(.25in)

  ==== `r cb$viz$header[cb$viz$var == "q8a"]`

  #figure(
    image("img/q8a.png", height: 3.5in),
    caption: [`r caps$q8a`]
  )

  `r extract_text(doc, "q8a", "p", "typst")`
]
```

```{=typst}
#page[
  == Mental health treatment

  `r extract_text(doc, "treatment", "p", "typst")`

  #v(.25in)

  ==== `r cb$viz$header[cb$viz$var == "q9"]`

  #figure(
    image("img/q9.png", height: 3in),
    caption: [`r caps$q9`]
  )

  `r extract_text(doc, "q9", "p", "typst")`

  #v(.25in)

  ==== `r cb$viz$header[cb$viz$var == "q10"]`

  #figure(
    image("img/q10.png", height: 3in),
    caption: [`r caps$q10`]
  )

  `r extract_text(doc, "q10", "p", "typst")`

  #v(.25in)

  ==== `r cb$viz$header[cb$viz$var == "q11"]`

  #figure(
    image("img/q11-pdf.png", height: 4.5in),
    caption: [`r caps$q11`]
  )

  `r extract_text(doc, "q11", "p", "typst")`

  #v(.25in)

  ==== `r cb$viz$header[cb$viz$var == "q12"]`

  #figure(
    image("img/q12.png", height: 3in),
    caption: [`r caps$q12`]
  )

  `r extract_text(doc, "q12", "p", "typst")`

  === Certified Community Behavioral Health Clinics

  `r extract_text(doc, "certified", "p", "typst")`

  #figure(
    image("img/map-ccbhc.png", height: 6in),
    caption: [`r caps$map_ccbhc`]
  )
]
```

```{=typst}
#page[
  == Emotional & social loneliness

  `r extract_text(doc, "loneliness", "p", "typst")`

  #v(.25in)

  ==== `r cb$viz$header[cb$viz$var == "lon_emo_bin"]`

  #figure(
    image("img/lon-emo-bin.png", height: 3.5in),
    caption: [`r caps$lon_emo_bin`]
  )

  `r #extract_text(doc, "", "p", "typst")`

  #v(.25in)

  ==== `r cb$viz$header[cb$viz$var == "lon_soc_bin"]`

  #figure(
    image("img/lon-soc-bin.png", height: 3.5in),
    caption: [`r caps$lon_soc_bin`]
  )

  `r #extract_text(doc, "", "p", "typst")`

  #v(.25in)

  ==== `r cb$viz$header[cb$viz$var == "lon_total_fac"]`

  #figure(
    image("img/lon-total-fac-pdf.png", height: 4in),
    caption: [`r caps$lon_total_fac`]
  )

  `r #extract_text(doc, "", "p", "typst")`

  #v(.25in)

  ==== `r cb$viz$header[cb$viz$var == "lon_total_bin"]`

  #figure(
    image("img/lon-total-bin.png", height: 3.5in),
    caption: [`r caps$lon_total_bin`]
  )

  `r #extract_text(doc, "", "p", "typst")`
]
```

```{=typst}
#page[
  == Social media use

  `r extract_text(doc, "media", "p", "typst")`

  #v(.25in)

  ==== `r cb$viz$header[cb$viz$var == "sm_add_bin"]`

  #figure(
    image("img/sm-add-bin.png", height: 3.5in),
    caption: [`r caps$sm_add_bin`]
  )

  `r extract_text(doc, "sm-add-bin", "p", "typst")`

  #v(.25in)

  ==== `r cb$viz$header[cb$viz$var == "sm_use_fac"]`

  #figure(
    image("img/sm-use-fac-pdf.png", height: 3.5in),
    caption: [`r caps$sm_use_fac`]
  )

  `r extract_text(doc, "sm-use-fac", "p", "typst")`

  #v(.25in)

  #figure(
    image("img/sm-use-bin-age-pdf.png", height: 4.5in),
    caption: [`r caps$sm_use_bin_age`]
  )

  `r extract_text(doc, "sm-use-bin-age", "p", "typst")`
]
```

```{=typst}
#page[
  == Sleep quality

  `r extract_text(doc, "quality", "p", "typst")`

  #v(.25in)

  ==== `r cb$viz$header[cb$viz$var == "hse"]`

  #figure(
    image("img/hse.png", height: 3.5in),
    caption: [`r caps$hse`]
  )

  `r extract_text(doc, "hse", "p", "typst")`

  #v(.25in)

  #figure(
    image("img/hse-age-pdf.png", height: 4.5in),
    caption: [`r caps$hse_age`]
  )

  `r extract_text(doc, "hse-age", "p", "typst")`

  #v(.25in)

  ==== `r cb$viz$header[cb$viz$var == "slp_dur_fac"]`

  #figure(
    image("img/slp-dur-fac-pdf.png", height: 3.5in),
    caption: [`r caps$slp_dur_fac`]
  )

  #v(.25in)

  #figure(
    table(image("img/tbl-slp-dur-stats.png", height: 1.4in)),
    caption: [`r caps$slp_dur_stats`]
  )

  `r extract_text(doc, "slp-dur-fac", "p", "typst")`

  #v(.25in)

  ==== `r cb$viz$header[cb$viz$var == "slp_lat"]`

  #figure(
    image("img/slp-lat-pdf.png", height: 3.5in),
    caption: [`r caps$slp_lat`]
  )

  #v(.25in)

  #figure(
    table(image("img/tbl-slp-lat.png", height: .84in)),
    caption: [`r caps$slp_lat_stats`]
  )

  `r extract_text(doc, "slp-lat", "p", "typst")`
]
```

```{=typst}
#page[
  = Conclusion

  `r extract_text(doc, "conclusion", "p", "typst")`
]
```

```{=typst}
#page[
  =
]
```







