---
title: "MH insights"
output: html_notebook
---

```{r setup}
knitr::opts_chunk$set(
  echo = FALSE,
  fig.width = 6,
  fig.height = 6
)
```

```{r message=FALSE}
library(tidyverse)
# library(setmeup)
library(kcData)
```

```{r}
source("fn.R")
```

```{r}
# Import data
mhfigs1 <- readRDS("../data/2-final/mh_figures_basic.rds")
mhfigs2 <- readRDS("../data/2-final/mh_figures_age.rds")
mhsurv <- readRDS("../data/2-final/mh_survey_results.rds")
cb <- readRDS("../data/2-final/mhs_codebook.rds")
ccbhc_sites <- readRDS("../data/2-final/ccbhc_sites.rds")
```

```{r}
kc_pal <- c("#318CCC", "#F04C43")
```

# Social isolation

```{r}
mhfigs1$q13_01$plot |>
  add_caption(mhfigs1$q13_01$cap)
```

```{r}
mhfigs2$q13_01$plot |>
  add_caption(mhfigs1$q13_01$cap)
```

# Social media use

```{r}
mhfigs1$q15$plot |>
  add_caption(mhfigs1$q15$cap)
```

```{r}
mhfigs2$q15$plot |>
  add_caption(mhfigs1$q15$cap)
```

# Sleep quality

```{r}
mhfigs1$q16$plot |>
  add_caption(mhfigs1$q16$cap)
```

```{r}
mhfigs2$q16$plot |>
  add_caption(mhfigs1$q16$cap)
```

# Mental health treatment

## Q9

```{r}
mhfigs1$q9$plot |>
  add_caption(mhfigs1$q9$cap)
```

## Q10

```{r}
mhfigs1$q10$plot  |>
  add_caption(mhfigs1$q10$cap)
```

```{r}
mhfigs1$q10a$plot  |>
  add_caption(mhfigs1$q10a$cap)
```

## Q11

```{r}
mhfigs1$q11$plot  |>
  add_caption(mhfigs1$q11$cap)
```

## Q12

```{r}
mhfigs1$q12$plot  |>
  add_caption(mhfigs1$q12$cap)
```

## CCBHC map

```{r fig.height=10}
ggplot(kcData::sf_city_2024) +
  geom_sf(linewidth = 1) +
  geom_point(
    data = mhsurv |> drop_na(q12),
    aes(x = block_lon, y = block_lat, color = q12),
    size = 1.5,
    alpha = .6
  ) +
  geom_sf(
    aes(color = "CCBHC"),
    data = ccbhc_sites[ccbhc_sites$city == "Kansas City", ],
    shape = 18,
    size = 4
  ) +
  scale_color_manual(values = c(kc_pal, "black")) +
  theme_void() +
  theme(
    # plot.title = ggtext::element_textbox_simple(),
    # plot.title = ggplot2::element_text(hjust = .5),
    # plot.title.position = "plot",
    # plot.caption = element_text(hjust = .5),
    # plot.caption.position = "plot",
    legend.text = element_text(size = rel(1)),
    legend.title = element_blank()
  ) #+
  # ggplot2::labs(caption = paste("n =", unique(mhsum$q12$total))) +
  # ggtitle(label = qtitle)
```




