---
title: "MH survey report plots"
output: html_notebook
---

# Purpose

Plots for the Mental Health Survey report.

# Set up environment and import data

```{r message=FALSE}
library(tidyverse)
library(setmeup)
```

```{r}
source("fn.R")
```

```{r}
# Survey results
cb <- readRDS("../data/2-final/mh_codebook.rds")
mhsurv <- readRDS("../data/2-final/mh_survey_results.rds")
```

# Prep data

```{r}
# Summarize results
qvars <- colnames(mhsurv)[grepl("^q\\d", colnames(mhsurv))]

mhsum <- lapply(qvars, \(x) {
  if (cb$key$code_score[cb$key$nm2 == x] != "yn") {
    mhsurv[[x]] <- factor(mhsurv[[x]], levels = rev(levels(mhsurv[[x]])))
  }
  summarize_results(mhsurv, var = x)
})

names(mhsum) <- qvars
```

```{r}
# Summarize Q11 question parts and join prompts
mhsum$q11 <- lapply(
  colnames(mhsurv)[grepl("^q11_\\d", colnames(mhsurv))],
  \(x) summarize_results(mhsurv, var = x) |>
    mutate(prompt = cb$prompts$prompt_abbr[cb$prompts$number == sub("q", "", x)]) |>
    rename(response = {{ x }})
)

names(mhsum$q11) <- colnames(mhsurv)[grepl("^q11_\\d", colnames(mhsurv))]

# Combine into one table
mhsum$q11 <- list_rbind(mhsum$q11)
```

```{r}
# Order question by percentage of "Yes" responses
lvl <- mhsum$q11 |>
  filter(response == "Yes") |>
  arrange(pct) |>
  pull(prompt)

mhsum$q11 <- mhsum$q11 |>
  mutate(prompt = factor(prompt, levels = lvl)) |>
  filter(response == "Yes")
```

```{r}
# Remove Q11 question parts and reorder `mhsum`
rng1 <- which(names(mhsum) == "q4_1"):which(names(mhsum) == "q10")
rng2 <- which(names(mhsum) == "q12"):which(names(mhsum) == "q17")
mhsum <- c(mhsum[rng1], mhsum["q11"], mhsum[rng2])
```

```{r}
# Summarize results grouped by age
qvars <- c("q13_01", "q15", "q16")

mhsum_age <- lapply(qvars, \(x) {
  summarize_results(mhsurv, var = x, gp_fctr = "age2")
})

names(mhsum_age) <- qvars
```

# Plots

```{r}
plots <- lapply(names(mhsum), \(x) {
  n <- sub("q", "", x)
  plot <- cb$prompts$plot[cb$prompts$number == n]
  if (plot == "bar") {
    scale <- cb$key$scale[cb$key$nm2 == x]
    fig <- mhsum[[x]] |>
      mutate(label = paste0(round_ties_away(pct), "%")) |>
      ggplot(aes(x = .data[[x]], y = pct, label = label, fill = .data[[x]])) |>
      mh_barplot(legend = FALSE) +
      scale_y_continuous(expand = c(0, NA)) +
      xlab(paste0("\n", scale)) + ylab("Sample (%)\n") +
      scale_x_discrete(labels = scales::label_wrap(16))
    if (grepl("(?i)score", scale)) {
      fig +
        scale_fill_manual(values = c("green", "yellow", "red"))
    } else {
      fig +
        scale_fill_viridis_d()
    }
  } else if (plot == "pie") {
    fig <- mhsum[[x]] |>
      mutate(label = paste0(round_ties_away(pct), "%")) |>
      ggplot(aes(x = "", y = pct, label = label, fill = .data[[x]])) |>
      mh_pie_chart()
  } else if (plot == "bar2") {
    fig <- mhsum[[x]] |>
      mutate(label = paste0(round_ties_away(pct), "%")) |>
      ggplot(aes(x = pct, y = prompt, label = label)) |>
      mh_barplot(fill = "#F04C43", legend = FALSE) +
      scale_x_continuous(expand = c(0, NA)) +
      xlab("\nSample (%)") + ylab("Reason\n") +
      scale_y_discrete(labels = scales::label_wrap(32))
  }
})

names(plots) <- names(mhsum)
```

```{r}
for (i in 1:length(plots)) print(plots[[i]])
```

## Age differences

```{r}
plots_age <- lapply(qvars, \(x) {
  mhsum_age[[x]] |>
    mutate(label = paste0(round_ties_away(pct), "%")) |>
    ggplot(aes(x = age2, y = pct, label = label, fill = .data[[x]])) |>
    mh_barplot(label_position = "stack") +
    # scale_y_continuous(expand = c(0, NA)) +
    xlab("\nAge") + ylab("Sample (%)\n") +
    scale_fill_viridis_d() +
    labs(fill = cb$key$scale[cb$key$nm2 == x])
})

names(plots_age) <- qvars

plots_age$q13_01 <- plots_age$q13_01 +
  coord_cartesian(ylim = c(NA, 110)) +
  scale_y_continuous(expand = c(0, NA), breaks = seq(0, 100, 25))
plots_age$q15 <- plots_age$q15 +
  coord_cartesian(ylim = c(NA, 105)) +
  scale_y_continuous(expand = c(0, NA), breaks = seq(0, 100, 25))
plots_age$q16 <- plots_age$q16 +
  coord_cartesian(ylim = c(90, 101)) +
  scale_y_continuous(expand = c(0, NA), breaks = c(90, 95, 100))
# plots_age$q16 <- plots_age$q16 +
#   coord_cartesian(ylim = c(90, NA)) +
#   scale_y_continuous(breaks = c(90, 95, 100))

for (i in 1:length(plots_age)) print(plots_age[[i]])
```

# Figure caption data

```{r}
# Get sample sizes
sampsize <- lapply(names(mhsum), \(x) {
  unique(mhsum[[x]]$total)
})

names(sampsize) <- names(mhsum)
```

```{r}
# Join question prompts and sample sizes
figcaps <- cb$prompts |>
  left_join(
    data.frame(
      number = sub("^q", "", unlist(names(sampsize))),
      sample_size = unlist(sampsize)
    ),
    by = "number"
  )
```

```{r}
figcaps <- figcaps |>
  filter(!is.na(sample_size)) |>
  select(number, caption, sample_size)

figcaps |>
  gt::gt()
```

# Save/export

```{r}
mh <- list(
  sum = mhsum,
  sum_age = mhsum_age,
  figs = plots,
  figs_age = plots_age,
  caps = figcaps
)
```

```{r}
saveRDS(mh, "../data/2-final/mh_report_data_&_plots.rds")
```

Save PNGs.

```{r include=FALSE}
# # Q4 subquestions
# lapply(names(plots_bar[grepl("^q4_", names(plots_bar))]), \(x) {
#   nm <- paste0("../output/mh-report/plot-", x, ".png")
#   ggsave(nm, plots_bar[[x]], width = 6.5, height = 3, bg = "white")
# })
# 
# # Q14-15
# lapply(names(plots_bar[grepl("^q14|^q15", names(plots_bar))]), \(x) {
#   nm <- paste0("../output/mh-report/plot-", x, ".png")
#   ggsave(nm, plots_bar[[x]], width = 4.5, height = 2, bg = "white")
# })
# 
# # All other bar plots
# lapply(names(plots_bar[!grepl("^q4_|^q14|^q15", names(plots_bar))]), \(x) {
#   nm <- paste0("../output/mh-report/plot-", x, ".png")
#   ggsave(nm, plots_bar[[x]], width = 6.5, height = 3, bg = "white")
# })
# 
# # All pie charts
# lapply(names(plots_pie), \(x) {
#   nm <- paste0("../output/mh-report/plot-", x, ".png")
#   ggsave(nm, plots_pie[[x]], width = 6.5, height = 3, bg = "white")
# })
# 
# # Q15 age differences
# lapply(names(plots_age[grepl("^q15", names(plots_age))]), \(x) {
#   nm <- paste0("../output/mh-report/plot-", x, "-age.png")
#   ggsave(nm, plots_age[[x]], width = 6.5, height = 3.5, bg = "white")
# })
# 
# # Q13 & Q16 age differences
# lapply(names(plots_age[!grepl("^q15", names(plots_age))]), \(x) {
#   nm <- paste0("../output/mh-report/plot-", x, "-age.png")
#   ggsave(nm, plots_age[[x]], width = 6.5, height = 3, bg = "white")
# })
# 
# # Q11
# ggsave(
#   "../output/mh-report/plot-q11.png",
#   plot_q11, width = 6.5, height = 4.2, bg = "white"
# )
# 
# # Q12
# ggsave(
#   "../output/mh-report/plot-q12.png",
#   plots_pie$q12, width = 6.5, height = 2, bg = "white"
# )
```
