---
title: "Plot selected questions grouped by age"
output: html_notebook
---

```{r message=FALSE}
library(tidyverse)
library(setmeup)
```

```{r include=FALSE}
lapply(list.files(pattern = "^fn"), source)
```

```{r}
mhsurv <- readRDS("../data/2-final/mh_survey_results.rds")
cb <- readRDS("../data/2-final/mhs_codebook.rds")
```

```{r}
vars <- c("si_bin", "sm_use_bin", "hse")

mhsmry <- lapply(vars, \(x) {
  summarize_results(mhsurv, var = x, gp_fctr = "age2")
})

names(mhsmry) <- vars
```

```{r}
figs <- imap(mhsmry, \(df, x) {
  n <- ifelse(x == "hse", 0, 5)
  os <- ifelse(x == "sm_use_bin", .8, 0)

  p <- df |>
    rename(age = age2) |>
    plot_grouped_data(x, "age", label_min = n, offset = os, dir = "v")

  if (x == "hse") {
    p <- p +
      coord_cartesian(ylim = c(90, 100)) +
      scale_y_continuous(
        expand = c(0, NA),
        breaks = c(90, 95, 100)
      ) +
      geom_text(
        aes(label = ifelse(
          df$hse == "No difficulty",
          paste0(round_ties_away(df$pct), "%"),
          NA
        )),
        position = position_nudge(y = -((df$pct - 90) / 2)),
        color = "white",
        fontface = "bold"
      )
  }

  p
})

names(figs) <- paste0(vars, "_age")

caps <- imap(mhsmry, \(df, x) {
  cap <- cap_text(df, x)
  
  if (x == "hse") {
    cap <- paste(cap, "Note the truncated y-axis scale.")
  }
  
  cap
})

names(caps) <- paste0(vars, "_age")
```

```{r fig.width=7, fig.height=4.5}
figs$si_bin_age
```

```{r fig.width=7, fig.height=4.5}
figs$sm_use_bin_age
```

```{r fig.width=7, fig.height=4.5}
figs$hse_age
```

# Save/export

```{r include=FALSE}
imap(figs, \(x, i) {
  i <- gsub("_", "-", i)
  ggsave(
    paste0("report/img/", i, ".png"), x,
    width = 7, height = 4, dpi = 100
  )
})
```

```{r include=FALSE}
imap(figs, \(x, i) {
  i <- paste0(gsub("_", "-", i), "-pdf")
  ggsave(
    paste0("report/img/", i, ".png"), x,
    width = 6.3, height = 3.5, dpi = 100
  )
})
```

```{r}
saveRDS(caps, "../data/2-final/figure_captions_questions_by_age.rds")
```
