---
title: "Plot MH questions"
output:
  html_notebook:
    css: "style.css"
---

```{r setup}
knitr::opts_chunk$set(
  echo = FALSE,
  dev = "png"
)

knitr::opts_knit$set(
  progress = FALSE,
  verbose = FALSE
)
```

```{r message=FALSE}
library(tidyverse)
library(setmeup)
```

```{r include=FALSE}
lapply(list.files(pattern = "^fn"), source)
```

```{r}
mhsurv <- readRDS("../data/2-final/mh_survey_results.rds")
cb <- readRDS("../data/2-final/mhs_codebook.rds")
```

```{r}
mhsmry <- summarize_dataset()
```

```{r}
figs <- imap(mhsmry, \(df, x) plot_data(df, x))
names(figs) <- names(mhsmry)

caps <- imap(mhsmry, \(df, x) cap_text(df, x))
names(caps) <- names(mhsmry)
```

```{r}
# Histogram for `slp_lat`
df <- mhsurv |>
  drop_na(slp_lat)

figs$slp_lat <- df |>
  ggplot(aes(x = slp_lat)) +
  geom_bar(fill = "#4f0a6b") +
  scale_x_binned(
    breaks = seq(0, 180, 5),
    expand = c(0, NA)
  ) +
  scale_y_continuous(
    breaks = seq(0, 140, 20),
    expand = c(0, NA)
  ) +
  labs(x = "\nSleep latency (minutes)", y = "Number of responses\n") +
  theme_classic() +
  theme(
    plot.background = element_rect(fill = NA, color = NA),
    panel.background = element_rect(fill = NA, color = NA),
    axis.line = element_line(color = "#555555"),
    axis.ticks = element_line(color = "#555555"),
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

caps$slp_lat <- paste0("N = ", nrow(df), ".")
```

```{r}
# Plot for PDF report with modified label text
figs$sm_use_fac2 <- plot_data(
  mhsmry$sm_use_fac,
  "sm_use_fac",
  label_text_size = 9
)
```

```{r fig.width=6, fig.height=3.5}
figs$q4_1
```

```{r fig.width=6, fig.height=3}
figs$q9
```

```{r fig.width=7, fig.height=4.5}
figs$q11
```

```{r fig.width=8, fig.height=3.5}
figs$lon_emo_fac
```

```{r}
caps$lon_emo_fac
```

```{r fig.width=5, fig.height=3.5}
figs$lon_emo_bin
```

```{r}
caps$lon_emo_bin
```

```{r fig.width=8, fig.height=3.5}
figs$lon_soc_fac
```

```{r}
caps$lon_soc_fac
```

```{r fig.width=5, fig.height=3.5}
figs$lon_soc_bin
```

```{r}
caps$lon_soc_bin
```

```{r}
figs$sm_use_fac2
```

```{r fig.width=8, fig.height=3.5}
rng <- list(
  c(1, 3),
  c(4, 9),
  c(10, 11),
  c(12, 12)
)

lbl <- c(
  "Not lonely",
  "Moderate lonely",
  "Severe\nlonely",
  "Very severe\nlonely"
)

figs$lon_total_fac <- figs$lon_total_fac |>
  add_brackets(
    axis = "x",
    range = rng,
    distance = -2.5,
    labels = lbl,
    label_offset = -.5
  ) +
  theme(axis.title.x = element_text(margin = margin(t = 25)))

figs$lon_total_fac
```

```{r}
caps$lon_total_fac
```

```{r fig.width=5.5, fig.height=3.5}
figs$lon_total_bin
```

```{r}
caps$lon_total_bin
```

```{r fig.width=8, fig.height=3.5}
figs$slp_lat
```

```{r}
dims <- list(
  vbar3 = list(w = 5, h = 3.5),
  vbar4 = list(w = 5.5, h = 3.5),
  vbar5 = list(w = 6, h = 3.5),
  vbarwide = list(w = 8, h = 3.5),
  vbarwide2 = list(w = 8, h = 4),
  vbarst = list(w = 7, h = 3.5),
  q11 = list(w = 7, h = 4.5),
  pie = list(w = 6, h = 3)
)

q <- list(
  q4_1 = dims$vbar5,
  q4_2 = dims$vbar5,
  q4_3 = dims$vbar5,
  q4_4 = dims$vbar5,
  q5 = dims$vbar5,
  q6 = dims$vbar5,
  q7 = dims$vbar3,
  q8a = dims$vbar3,
  q9 = dims$pie,
  q10 = dims$pie,
  q11 = dims$q11,
  q12 = dims$pie,
  lon_emo_fac = dims$vbarwide,
  lon_emo_bin = dims$vbar3,
  lon_soc_fac = dims$vbarwide,
  lon_soc_bin = dims$vbar3,
  lon_total_fac = dims$vbarwide2,
  lon_total_bin = dims$vbar4,
  si_bin = dims$vbar3,
  sm_add_bin = dims$vbar3,
  sm_use_fac = dims$vbarwide,
  hse = dims$vbar4,
  slp_dur_fac = dims$vbarwide,
  slp_lat = dims$vbarwide
)
```

```{r include=FALSE}
imap(q, \(x, i) {
  i2 <- gsub("_", "-", i)
  ggsave(
    paste0("report/img/", i2, ".png"), figs[[i]],
    width = x$w, height = x$h, dpi = 100
  )
})
```

```{r}
dims <- lapply(dims, \(x) {
  if (x$w > 6.3) {
    x$w <- 6.3
    x
  } else {
    NULL
  }
})

dims <- compact(dims)

q <- list(
  q11 = dims$q11,
  lon_emo_fac = dims$vbarwide,
  lon_soc_fac = dims$vbarwide,
  lon_total_fac = dims$vbarwide2,
  sm_use_fac2 = dims$vbarwide,
  slp_dur_fac = dims$vbarwide,
  slp_lat = dims$vbarwide
)
```

```{r include=FALSE}
imap(q, \(x, i) {
  i2 <- paste0(gsub("_", "-", i), "-pdf")
  ggsave(
    paste0("report/img/", i2, ".png"), figs[[i]],
    width = x$w, height = x$h, dpi = 100
  )
})
```

```{r}
saveRDS(caps, "../data/2-final/figure_captions_questions.rds")
```
