---
title: "Tests for differences by sex"
output:
  html_notebook:
    toc: false
---

```{r setup}
# knitr::opts_chunk$set(
#   echo = FALSE,
#   fig.width = 10,
#   fig.height = 5
# )
```

```{r message=FALSE}
library(tidyverse)
library(gt, exclude = "pct")
```

```{r}
mhsurv <- readRDS("../data/2-final/mh_survey_results.rds")
cb <- readRDS("../data/2-final/mhs_codebook.rds")
```

```{r}
vars <- cb$key |>
  filter(group == "mh", !grepl("_fac$|^si_", var2)) |>
  pull(var2)
```

# Analysis

T-tests are performed on all questions. When the question has factor data, it's first converted to numeric. Chi-squared tests are performed on questions with factor data only (rating scales, yes/no, etc.).

```{r}
ls <- lapply(vars, \(x) {
  df <- mhsurv |>
    rename(var = all_of(x)) |>
    select(birth_sex, var) |>
    drop_na()

  # T-test
  dft <- df |>
    mutate(var = as.numeric(var))

  dft <- t.test(var ~ birth_sex, data = dft) |>
    broom::tidy() |>
    relocate(method)
  
  # Chi-squared test
  if (is.factor(df$var)) {
    dfx <- df |>
      count(birth_sex, var, .drop = FALSE) |>
      replace_na(list(n = 0)) |>
      pivot_wider(
        names_from = var,
        values_from = n
      ) |>
      column_to_rownames("birth_sex")

    dfx <- dfx |>
      chisq.test() |>
      broom::tidy() |>
      relocate(method)
  } else {
    dfx <- chisq.test(data.frame(x = c(1, 1), y = c(1, 1))) |>
      broom::tidy()
    
    dfx[!is.na(dfx)] <- NA
  }
  
  # Join results
  full_join(dft, dfx, by = join_by(method, statistic, p.value, parameter)) |>
    mutate(question = x, .before = 1)
})

results <- list_rbind(ls)
```

```{r}
# Pull question text
q11text <- cb$viz |>
  filter(grepl("^q11_", var)) |>
  mutate(text = paste0(
    str_to_sentence(nickname), " (", prompt_abbr, ".)"
  )) |>
  select(var, text)

qtext <- cb$viz |>
  filter(var %in% vars) |>
  mutate(text = paste0(str_to_sentence(nickname), " (", header, ")")) |>
  select(var, text) |>
  rows_update(q11text, by = "var")

results <- results |>
  left_join(qtext, by = c("question" = "var"))
```

```{r}
p <- c(
  "(?i)Pearson's Chi-squared test" = "$χ^2$",
  "(?i)Welch two sample t-test" = "T-test"
)

results |>
  mutate(
    method = str_replace_all(method, p)
  ) |>
  select(-question) |>
  gt(groupname_col = "text") |>
  fmt_markdown("method") |>
  tab_style(
    style = cell_fill("lightgreen"),
    locations = cells_body(
      rows = p.value < .05,
      columns = p.value
    )
  ) |>
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_row_groups()
  ) |>
  tab_options(container.height = px(1000)) |>
  opt_stylize(style = 6, color = "gray")
```

# Key

```{r}
vars_fctr <- vars[sapply(vars, \(x) is.factor(mhsurv[[x]]))]

fctr_levels <- lapply(vars_fctr, \(x) {
  data.frame(
    number = as.numeric(na.omit(fct_unique(mhsurv[[x]]))),
    response = as.character(na.omit(fct_unique(mhsurv[[x]])))
  )
})

names(fctr_levels) <- vars_fctr
```

```{r}
fctrs_unq <- lapply(fctr_levels, \(x) {
  imap(fctr_levels, \(y, i) {
    if (isTRUE(all.equal(x, y))) {
      i
    }
  }) |>
    compact() |>
    unlist()
}) |>
  unique()
```

```{r}
fctr_levels <- lapply(fctrs_unq, \(x) {
  t <- which(names(fctr_levels) == x[1])
  
  n <- cb$viz |>
    filter(var %in% x) |>
    pull(nickname) |>
    unique() |>
    str_to_sentence()
  
  fctr_levels[[t]] |>
    gt() |>
    tab_header(paste(n, collapse = ", "))
})
```

Numeric levels for sex.

```{r}
data.frame(
  number = as.numeric(na.omit(fct_unique(mhsurv$birth_sex))),
  group = as.character(na.omit(fct_unique(mhsurv$birth_sex)))
) |>
  gt()
```

Numeric levels for factor responses.

```{r}
fctr_levels
```


