---
title: "Plots: Social media use"
output: html_notebook
---

```{r setup}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.height = 4
)
```

```{r message=FALSE}
library(tidyverse)
library(readxl)
```

```{r}
source("fn.R")
```

```{r}
mh <- readRDS("../data/2-final/scored_results.rds")
bhc <- readRDS("../data/2-aux/behavioral_health_centers.rds")
demo <- readRDS("../data/2-final/survey_demographic_data.rds")
```

# Q14: Social media addiction score

## Race

```{r}
mh$q14 |>
  drop_na(q14_raw, race3) |>
  ggplot(aes(x = race3, y = q14_raw)) +
  geom_boxplot()
```

## Gender

```{r}
mh$q14 |>
  drop_na(q14_raw, birth_gender) |>
  ggplot(aes(x = birth_gender, y = q14_raw)) +
  geom_boxplot()
```

```{r}
mh$q14 |>
  drop_na(q14_raw, birth_gender) |>
  ggplot(aes(x = q14_raw, fill = birth_gender)) +
  geom_histogram(position = "identity", alpha = .6, binwidth = 5) +
  scale_fill_manual(values = c("#2166ac", "#b2182b"))
```

## Age

```{r}
mh$q14 |>
  drop_na(q14_raw, age_group) |>
  ggplot(aes(x = age_group, y = q14_raw)) +
  geom_boxplot()
```

# Q15: Hours spent on social media

## Race

```{r}
mh$q15 |>
  drop_na(q15_raw, race3) |>
  ggplot(aes(x = race3, y = q15_raw)) +
  geom_boxplot()
```

## Gender

```{r}
mh$q15 |>
  drop_na(q15_raw, birth_gender) |>
  ggplot(aes(x = birth_gender, y = q15_raw)) +
  geom_boxplot()
```

```{r}
mh$q15 |>
  drop_na(q15_raw, birth_gender) |>
  ggplot(aes(x = q15_raw, fill = birth_gender)) +
  geom_histogram(position = "identity", alpha = .6, binwidth = 5) +
  scale_fill_manual(values = c("#2166ac", "#b2182b"))
```

## Age

```{r}
mh$q15 |>
  drop_na(q15_raw, age_group) |>
  ggplot(aes(x = age_group, y = q15_raw)) +
  geom_boxplot()
```

# Hours used vs addiction score

```{r}
sm <- demo |>
  left_join(
    mh$q14 |>
      select(id, score = q14_raw),
    by = "id"
  ) |>
  left_join(
    mh$q15 |>
      select(id, hours = q15_raw),
    by = "id"
  ) |>
  drop_na(score, hours)
```

## All respondents

```{r}
sm_results <- lm(hours ~ score, data = sm)

summary(sm_results)
```

```{r}
sm |>
  ggplot(aes(x = hours, y = score)) +
  geom_point() +
  xlab("Social media addiction score") +
  ylab("Hours spent on social media") +
  expand_limits(x = 0) +
  geom_smooth(method = lm)
```

## Women

```{r}
sm_female <- sm |>
  filter(birth_gender == "Female")

sm_results_female <- lm(hours ~ score, data = sm_female)

summary(sm_results_female)
```

```{r}
sm_female |>
  ggplot(aes(x = hours, y = score)) +
  geom_point() +
  xlab("Social media addiction score") +
  ylab("Hours spent on social media") +
  expand_limits(x = 0) +
  geom_smooth(method = lm)
```

## Men

```{r}
sm_male <- sm |>
  filter(birth_gender == "Male")

sm_results_male <- lm(hours ~ score, data = sm_male)

summary(sm_results_male)
```

```{r}
sm_male |>
  ggplot(aes(x = hours, y = score)) +
  geom_point() +
  xlab("Social media addiction score") +
  ylab("Hours spent on social media") +
  expand_limits(x = 0) +
  geom_smooth(method = lm)
```

# Q16.3 Hours slept

## Race

```{r}
mh$q16 |>
  drop_na(q16.3, race3) |>
  ggplot(aes(x = race3, y = q16.3)) +
  geom_boxplot()
```

## Gender

```{r}
mh$q16 |>
  drop_na(q16.3, birth_gender) |>
  ggplot(aes(x = birth_gender, y = q16.3)) +
  geom_boxplot()
```

## Age

```{r}
mh$q16 |>
  drop_na(q16.3, age_group) |>
  ggplot(aes(x = age_group, y = q16.3)) +
  geom_boxplot()
```





